#!/usr/bin/env python3
"""
Claims ledger: every headline number is checked against the results files.

``claims/claims.json`` lists each claim the project has made, its current status
(supported, replicated, revised, not replicated, retracted, open), and the numbers
it quotes. Each number names the results file and JSON pointer it comes from and
the value as stated. This tool

    check    resolves every pointer, verifies that the data round to the stated
             value, and verifies that the README's evidence table and
             docs/CLAIMS.md are exactly what the ledger renders; exits 1 otherwise
    render   rewrites the README table (between the claims markers) and docs/CLAIMS.md

So a number in the README cannot drift from the data, and a claim cannot be
quietly dropped: retracted and unreplicated claims stay in the ledger with their
evidence.

    python tools/claims.py check
    python tools/claims.py render
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "claims" / "claims.json"
README = ROOT / "README.md"
CLAIMS_MD = ROOT / "docs" / "CLAIMS.md"
START, END = "<!-- claims:start (generated by tools/claims.py; edit claims/claims.json) -->", "<!-- claims:end -->"

STATUS_ORDER = ["replicated", "supported", "revised", "open", "not replicated", "retracted"]


def resolve(doc, pointer: str):
    """RFC 6901 JSON pointer."""
    cur = doc
    for raw in pointer.lstrip("/").split("/"):
        key = raw.replace("~1", "/").replace("~0", "~")
        cur = cur[int(key)] if isinstance(cur, list) else cur[key]
    return cur


def _fmt(v, decimals):
    if isinstance(v, bool) or isinstance(v, str) or decimals is None:
        return str(v)
    if decimals == "int":
        return str(int(round(v)))
    return f"{v:.{decimals}f}"


def load() -> Dict:
    return json.loads(LEDGER.read_text(encoding="utf-8"))


def check_numbers(ledger: Dict) -> List[str]:
    errors, cache = [], {}
    for c in ledger["claims"]:
        for name, ev in c.get("evidence", {}).items():
            path = ROOT / ev["file"]
            try:
                doc = cache.setdefault(ev["file"], json.loads(path.read_text(encoding="utf-8")))
                actual = resolve(doc, ev["pointer"])
            except (OSError, KeyError, IndexError, ValueError, TypeError) as e:
                errors.append(f"{c['id']}.{name}: cannot resolve {ev['file']}#{ev['pointer']} ({e!r})")
                continue
            stated = ev["value"]
            d = ev.get("decimals", 2)
            if isinstance(stated, (bool, str)) or d is None:
                ok = actual == stated
            else:
                ok = _fmt(actual, d) == _fmt(stated, d) or (d != "int" and abs(float(actual) - float(stated)) <= 0.5 * 10 ** -d + 1e-12)
            if not ok:
                errors.append(f"{c['id']}.{name}: stated {stated!r}, data say {actual!r} ({ev['file']}#{ev['pointer']})")
        for name in re.findall(r"\{(\w+)\}", c.get("evidence_text", "")):
            if name not in c.get("evidence", {}):
                errors.append(f"{c['id']}: evidence_text uses {{{name}}} with no evidence entry")
    return errors


def _text(c: Dict) -> str:
    vals = {k: _fmt(ev["value"], ev.get("decimals", 2)) for k, ev in c.get("evidence", {}).items()}
    return c.get("evidence_text", "").format(**vals)


def render_table(ledger: Dict) -> str:
    rows = ["| claim | introduced | status | evidence |", "|---|---|---|---|"]
    for c in ledger["claims"]:
        claim = f"**{c['claim']}**" if c.get("headline") else c["claim"]
        rows.append(f"| {claim} | v{c['introduced']} | **{c['status']}** | {_text(c)} |")
    return "\n".join([START, "", *rows, "", END])


def render_md(ledger: Dict) -> str:
    L = ["# Claims ledger", "",
         "Generated by `tools/claims.py` from `claims/claims.json`. Every number below is checked in CI against "
         "the results file and JSON pointer it cites; a claim that fails to replicate keeps its entry with a "
         "changed status instead of disappearing.", ""]
    counts = {s: sum(c["status"] == s for c in ledger["claims"]) for s in STATUS_ORDER}
    L.append("Status counts: " + ", ".join(f"{s}: {n}" for s, n in counts.items() if n) + "\n")
    for c in ledger["claims"]:
        L.append(f"## {c['id']}: {c['claim']}\n")
        L.append(f"- introduced: v{c['introduced']} · status: **{c['status']}**")
        if c.get("history"):
            L.append(f"- history: {c['history']}")
        L.append(f"- evidence: {_text(c)}")
        for name, ev in c.get("evidence", {}).items():
            L.append(f"  - `{name}` = {_fmt(ev['value'], ev.get('decimals', 2))} ← `{ev['file']}` `{ev['pointer']}`")
        L.append("")
    return "\n".join(L).rstrip() + "\n"


def _readme_parts() -> Tuple[str, str, str]:
    text = README.read_text(encoding="utf-8")
    i, j = text.find(START), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit("README.md has no claims markers")
    return text[:i], text[i:j + len(END)], text[j + len(END):]


def check() -> List[str]:
    ledger = load()
    errors = check_numbers(ledger)
    ids = [c["id"] for c in ledger["claims"]]
    if len(ids) != len(set(ids)):
        errors.append("duplicate claim ids")
    for c in ledger["claims"]:
        if c["status"] not in STATUS_ORDER:
            errors.append(f"{c['id']}: unknown status {c['status']!r}")
    _, block, _ = _readme_parts()
    if block != render_table(ledger):
        errors.append("README evidence table differs from the ledger (run: python tools/claims.py render)")
    if not CLAIMS_MD.exists() or CLAIMS_MD.read_text(encoding="utf-8") != render_md(ledger):
        errors.append("docs/CLAIMS.md differs from the ledger (run: python tools/claims.py render)")
    return errors


def render() -> None:
    ledger = load()
    errors = check_numbers(ledger)
    if errors:
        raise SystemExit("refusing to render; stated numbers do not match the data:\n  " + "\n  ".join(errors))
    head, _, tail = _readme_parts()
    README.write_text(head + render_table(ledger) + tail, encoding="utf-8")
    CLAIMS_MD.write_text(render_md(ledger), encoding="utf-8")


def main(argv: List[str]) -> None:
    cmd = argv[1] if len(argv) > 1 else "check"
    if cmd == "render":
        render()
        print("rendered README.md table and docs/CLAIMS.md")
    elif cmd == "check":
        errors = check()
        if errors:
            print("claims ledger FAILED:\n  " + "\n  ".join(errors))
            sys.exit(1)
        print(f"claims ledger OK ({len(load()['claims'])} claims, every number matches its source)")
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main(sys.argv)
