#!/usr/bin/env python3
"""
Claims ledger: every headline number is checked against the results files.

``claims/claims.json`` lists each claim the project has made, its current status
(supported, replicated, revised, not replicated, retracted, open), and the numbers
it quotes. Each number names the results file and JSON pointer it comes from and
the value as stated. This tool

    check    resolves every pointer, verifies that the data round to the stated
             value, and verifies that the README's evidence table and
             docs/CLAIMS.md are exactly what the ledger renders; exits 1 otherwise
    render   rewrites the README table (between the claims markers), docs/CLAIMS.md and
             docs/index.html (a self-contained evidence explorer for GitHub Pages)

So a number in the README cannot drift from the data, and a claim cannot be
quietly dropped: retracted and unreplicated claims stay in the ledger with their
evidence.

    python tools/claims.py check
    python tools/claims.py render
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "claims" / "claims.json"
README = ROOT / "README.md"
CLAIMS_MD = ROOT / "docs" / "CLAIMS.md"
EXPLORER = ROOT / "docs" / "index.html"
REPO_URL = "https://github.com/kai9987kai/GhostInTheMachine/blob/main/"
START, END = "<!-- claims:start (generated by tools/claims.py; edit claims/claims.json) -->", "<!-- claims:end -->"

STATUS_ORDER = ["replicated", "supported", "revised", "open", "not replicated", "retracted"]


def resolve(doc, pointer: str):
    """RFC 6901 JSON pointer."""
    cur = doc
    for raw in pointer.lstrip("/").split("/"):
        key = raw.replace("~1", "/").replace("~0", "~")
        cur = cur[int(key)] if isinstance(cur, list) else cur[key]
    return cur


def _fmt(v, decimals):
    if isinstance(v, bool) or isinstance(v, str) or decimals is None:
        return str(v)
    if decimals == "int":
        return str(int(round(v)))
    return f"{v:.{decimals}f}"


def load() -> Dict:
    return json.loads(LEDGER.read_text(encoding="utf-8"))


def check_numbers(ledger: Dict) -> List[str]:
    errors, cache = [], {}
    for c in ledger["claims"]:
        for name, ev in c.get("evidence", {}).items():
            path = ROOT / ev["file"]
            try:
                doc = cache.setdefault(ev["file"], json.loads(path.read_text(encoding="utf-8")))
                actual = resolve(doc, ev["pointer"])
            except (OSError, KeyError, IndexError, ValueError, TypeError) as e:
                errors.append(f"{c['id']}.{name}: cannot resolve {ev['file']}#{ev['pointer']} ({e!r})")
                continue
            stated = ev["value"]
            d = ev.get("decimals", 2)
            if isinstance(stated, (bool, str)) or d is None:
                ok = actual == stated
            else:
                ok = _fmt(actual, d) == _fmt(stated, d) or (d != "int" and abs(float(actual) - float(stated)) <= 0.5 * 10 ** -d + 1e-12)
            if not ok:
                errors.append(f"{c['id']}.{name}: stated {stated!r}, data say {actual!r} ({ev['file']}#{ev['pointer']})")
        for name in re.findall(r"\{(\w+)\}", c.get("evidence_text", "")):
            if name not in c.get("evidence", {}):
                errors.append(f"{c['id']}: evidence_text uses {{{name}}} with no evidence entry")
    return errors


def _text(c: Dict) -> str:
    vals = {k: _fmt(ev["value"], ev.get("decimals", 2)) for k, ev in c.get("evidence", {}).items()}
    return c.get("evidence_text", "").format(**vals)


def render_table(ledger: Dict) -> str:
    rows = ["| claim | introduced | status | evidence |", "|---|---|---|---|"]
    for c in ledger["claims"]:
        claim = f"**{c['claim']}**" if c.get("headline") else c["claim"]
        rows.append(f"| {claim} | v{c['introduced']} | **{c['status']}** | {_text(c)} |")
    return "\n".join([START, "", *rows, "", END])


def render_md(ledger: Dict) -> str:
    L = ["# Claims ledger", "",
         "Generated by `tools/claims.py` from `claims/claims.json`. Every number below is checked in CI against "
         "the results file and JSON pointer it cites; a claim that fails to replicate keeps its entry with a "
         "changed status instead of disappearing.", ""]
    counts = {s: sum(c["status"] == s for c in ledger["claims"]) for s in STATUS_ORDER}
    L.append("Status counts: " + ", ".join(f"{s}: {n}" for s, n in counts.items() if n) + "\n")
    for c in ledger["claims"]:
        L.append(f"## {c['id']}: {c['claim']}\n")
        L.append(f"- introduced: v{c['introduced']} · status: **{c['status']}**")
        if c.get("history"):
            L.append(f"- history: {c['history']}")
        L.append(f"- evidence: {_text(c)}")
        for name, ev in c.get("evidence", {}).items():
            L.append(f"  - `{name}` = {_fmt(ev['value'], ev.get('decimals', 2))} ← `{ev['file']}` `{ev['pointer']}`")
        L.append("")
    return "\n".join(L).rstrip() + "\n"


_CSS = """
:root { --bg:#fbfaf7; --surface:#ffffff; --ink:#15140f; --ink2:#55534b; --line:#e3e1d8; --accent:#2a64c5;
  --replicated:#1f7a4d; --supported:#2a64c5; --revised:#a36a00; --open:#6b6b6b; --notrep:#b4462c; --retracted:#8a2d1c; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --bg:#15140f; --surface:#1e1d18; --ink:#f2f0e8;
  --ink2:#b6b3a8; --line:#34322b; --accent:#7fa8f0; --replicated:#5cc08d; --supported:#7fa8f0; --revised:#e0a93b;
  --open:#a3a3a3; --notrep:#ec8a6f; --retracted:#e07a63; } }
:root[data-theme="dark"] { --bg:#15140f; --surface:#1e1d18; --ink:#f2f0e8; --ink2:#b6b3a8; --line:#34322b; --accent:#7fa8f0;
  --replicated:#5cc08d; --supported:#7fa8f0; --revised:#e0a93b; --open:#a3a3a3; --notrep:#ec8a6f; --retracted:#e07a63; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--ink); font:16px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif; }
main { max-width: 960px; margin: 0 auto; padding: 32px 16px 64px; }
h1 { font-size: 1.7rem; line-height:1.25; margin: 0 0 8px; }
.lede { color: var(--ink2); margin: 0 0 20px; max-width: 70ch; }
.note { border-left: 3px solid var(--line); padding: 4px 12px; color: var(--ink2); font-size: .92rem; margin: 0 0 24px; }
.counts { display:flex; flex-wrap:wrap; gap:8px; margin: 0 0 16px; }
.filter { border:1px solid var(--line); background:var(--surface); color:var(--ink); border-radius:999px; padding:6px 12px;
  font: inherit; font-size:.9rem; cursor:pointer; }
.filter[aria-pressed="true"] { border-color: var(--ink); }
.card { background:var(--surface); border:1px solid var(--line); border-radius:10px; padding:16px 18px; margin: 12px 0; }
.card h2 { font-size:1.05rem; margin:0 0 6px; line-height:1.35; }
.meta { display:flex; flex-wrap:wrap; gap:8px; align-items:center; font-size:.85rem; color:var(--ink2); margin-bottom:8px; }
.chip { font-weight:600; border-radius:999px; padding:1px 9px; border:1px solid currentColor; }
.s-replicated{color:var(--replicated)} .s-supported{color:var(--supported)} .s-revised{color:var(--revised)}
.s-open{color:var(--open)} .s-not-replicated{color:var(--notrep)} .s-retracted{color:var(--retracted)}
.history { color: var(--ink2); font-size:.92rem; }
details { margin-top:8px; font-size:.85rem; }
summary { cursor:pointer; color: var(--accent); }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size:.82rem; overflow-wrap:anywhere; }
ul.src { padding-left: 18px; margin: 6px 0 0; }
a { color: var(--accent); }
footer { margin-top: 32px; color: var(--ink2); font-size:.85rem; }
"""

_JS = """
const buttons = document.querySelectorAll('.filter');
buttons.forEach(b => b.addEventListener('click', () => {
  const want = b.dataset.status;
  buttons.forEach(x => x.setAttribute('aria-pressed', String(x === b)));
  document.querySelectorAll('.card').forEach(c => { c.hidden = !(want === 'all' || c.dataset.status === want); });
}));
"""


def render_explorer(ledger: Dict) -> str:
    e = html.escape
    cards = []
    for c in ledger["claims"]:
        slug = c["status"].replace(" ", "-")
        srcs = "".join(
            f'<li><code>{e(name)} = {e(_fmt(ev["value"], ev.get("decimals", 2)))}</code> from '
            f'<a href="{REPO_URL}{e(ev["file"])}">{e(ev["file"])}</a> <code>{e(ev["pointer"])}</code></li>'
            for name, ev in c.get("evidence", {}).items())
        hist = f'<p class="history">{e(c["history"])}</p>' if c.get("history") else ""
        cards.append(
            f'<article class="card" data-status="{e(slug)}" id="{e(c["id"])}">'
            f'<div class="meta"><span class="chip s-{e(slug)}">{e(c["status"])}</span>'
            f'<span>introduced in v{e(c["introduced"])}</span><span>{e(c["id"])}</span></div>'
            f'<h2>{e(c["claim"])}</h2><p>{e(_text(c))}</p>{hist}'
            f'<details><summary>Where each number comes from</summary><ul class="src">{srcs}</ul></details></article>')
    counts = {s: sum(c["status"] == s for c in ledger["claims"]) for s in STATUS_ORDER}
    buttons = ['<button class="filter" data-status="all" aria-pressed="true">all ' + str(len(ledger["claims"])) + '</button>']
    buttons += [f'<button class="filter" data-status="{s.replace(" ", "-")}" aria-pressed="false">{e(s)} {n}</button>'
                for s, n in counts.items() if n]
    return ("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<title>Ghost in the Machine: claims ledger</title>"
            f"<style>{_CSS}</style></head><body><main>"
            "<h1>Ghost in the Machine: what the evidence supports</h1>"
            "<p class=\"lede\">Every claim this project has made about its synthetic agent, with its current status "
            "and the exact results file and field behind each number. Claims that were retracted or revised stay here. "
            "CI fails if any number drifts from its data.</p>"
            "<p class=\"note\">Synthetic computational experiments. Nothing here creates, detects, measures or proves "
            "consciousness in any system.</p>"
            f"<div class=\"counts\" role=\"group\" aria-label=\"Filter by status\">{''.join(buttons)}</div>"
            + "".join(cards) +
            f"<footer>Generated by <code>tools/claims.py</code> from <a href=\"{REPO_URL}claims/claims.json\">claims/claims.json</a>. "
            f"Source: <a href=\"https://github.com/kai9987kai/GhostInTheMachine\">github.com/kai9987kai/GhostInTheMachine</a>.</footer>"
            f"</main><script>{_JS}</script></body></html>\n")


def _readme_parts() -> Tuple[str, str, str]:
    text = README.read_text(encoding="utf-8")
    i, j = text.find(START), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit("README.md has no claims markers")
    return text[:i], text[i:j + len(END)], text[j + len(END):]


def check() -> List[str]:
    ledger = load()
    errors = check_numbers(ledger)
    ids = [c["id"] for c in ledger["claims"]]
    if len(ids) != len(set(ids)):
        errors.append("duplicate claim ids")
    for c in ledger["claims"]:
        if c["status"] not in STATUS_ORDER:
            errors.append(f"{c['id']}: unknown status {c['status']!r}")
    _, block, _ = _readme_parts()
    if block != render_table(ledger):
        errors.append("README evidence table differs from the ledger (run: python tools/claims.py render)")
    if not CLAIMS_MD.exists() or CLAIMS_MD.read_text(encoding="utf-8") != render_md(ledger):
        errors.append("docs/CLAIMS.md differs from the ledger (run: python tools/claims.py render)")
    if not EXPLORER.exists() or EXPLORER.read_text(encoding="utf-8") != render_explorer(ledger):
        errors.append("docs/index.html differs from the ledger (run: python tools/claims.py render)")
    return errors


def render() -> None:
    ledger = load()
    errors = check_numbers(ledger)
    if errors:
        raise SystemExit("refusing to render; stated numbers do not match the data:\n  " + "\n  ".join(errors))
    head, _, tail = _readme_parts()
    README.write_text(head + render_table(ledger) + tail, encoding="utf-8")
    CLAIMS_MD.write_text(render_md(ledger), encoding="utf-8")
    EXPLORER.write_text(render_explorer(ledger), encoding="utf-8")


def main(argv: List[str]) -> None:
    cmd = argv[1] if len(argv) > 1 else "check"
    if cmd == "render":
        render()
        print("rendered README.md table, docs/CLAIMS.md and docs/index.html")
    elif cmd == "check":
        errors = check()
        if errors:
            print("claims ledger FAILED:\n  " + "\n  ".join(errors))
            sys.exit(1)
        print(f"claims ledger OK ({len(load()['claims'])} claims, every number matches its source)")
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main(sys.argv)
